### ISSUE TITLE
Seção de Pentest

### ISSUE THREAD

**Issue by LaurianoElmiroDuarte** [OfficialMarinho/Links-uteis#1]
eu quero dar uma dica aos contribuidores, vamos inserir ferramentas de pentest usadas em fronted, abraços .

**Comment by OfficialMarinho** [comment]
É uma ótima ideia, @LaurianoElmiroDuarte ! Caso queira fazer uma pull request para colaborar, ficarei grato! :octocat:

**Comment by LaurianoElmiroDuarte** [comment]
farei sim abraços @OfficialMarinho

**Comment by OfficialMarinho** [comment]
> farei sim abraços @OfficialMarinho

Fico agradecido! Ficarei no aguardo para fazer o merge ;)
