### ISSUE TITLE
Tópico correto para guias

### ISSUE THREAD

**Issue by TeijiW** [OfficialMarinho/Links-uteis#10]
Qual seria o local correto de adicionar links para guias? Como por exemplo "JS: A forma certa" ou "Git - Guia prático"?

**Comment by OfficialMarinho** [comment]
Olá, Teiji!

Trata-se de conteúdos educacionais gratuitos?

**Comment by TeijiW** [comment]
Sim, guias feitos para ensinar e disponibilizados de maneira totalmente gratuita, sem pirataria.

**Comment by OfficialMarinho** [comment]
Faça uma pull request na categoria estudos.
