### ISSUE TITLE
Corrigir a sintaxe de link na seção Hosting

### ISSUE THREAD

**Issue by micalevisk** [OfficialMarinho/Links-uteis#14]
O item da **linha 146** ([desta versão](https://github.com/OfficialMarinho/Links-uteis/tree/ba853637e2e0f2f00f304fe3bfd525b21a744e1d)) está
```
(One.com)[https://www.one.com/pt-BR/]
```
quando deveria ser
```
[One.com](https://www.one.com/pt-BR/)
```

**Comment by OfficialMarinho** [comment]
Muito bem observado, Micael! Já corrigi o problema. Muito obrigado! ;)
