### ISSUE TITLE
Links para outros repositórios

### ISSUE THREAD

**Issue by TeijiW** [OfficialMarinho/Links-uteis#17]
Encontrei um repositório cujo qual há vários canais do Youtube (brasileiros) que falam sobre determinados assuntos/tópicos/tecnologias relacionados a programação.
Há algum problema em fazer a linkagem para outro repositório?

**Comment by OfficialMarinho** [comment]
Oi, Teiji!

Sem problemas. Mas, caso deseje fazer uma PR para adicionar uma nova categoria aos links, certifique-se de adicionar no final do arquivo e com bons links que seguem o padrão de qualidade do repositório.
