### ISSUE TITLE
Perfis no Twitter

### ISSUE THREAD

**Issue by mayronceccon** [OfficialMarinho/Links-uteis#53]
Boa tarde, seria interessante criar um tópico de perfis do Twitter de pessoas relevantes na área de tecnologia!

**Comment by OfficialMarinho** [comment]
Oi, Mayron!

Não existem tantos conteúdos de programação BR no Twitter. A galera está mais ativa no YouTube e em grupos no Facebook e Telegram.

**Comment by mayronceccon** [comment]
Minha idéia era de perfis de pessoas não de grupos.

**Comment by OfficialMarinho** [comment]
Como dito, não existem tantos conteúdos de programação BR no Twitter. É mais comum ver contas com conteúdos úteis e que agregam conhecimento em canais no YouTube e grupos nos aplicativos de mensagem.

A maioria dos desenvolvedores e grandes personalidades da tecnologia brasileira não criam conteúdo relevante (especificamente no Twitter) suficiente para criarmos uma categoria deste nível. Espero que entenda! :wink:
