### ISSUE TITLE
Ordenar em ordem alfabética 

### ISSUE THREAD

**Issue by Codfect** [OfficialMarinho/Links-uteis#69]
Alguém conhece uma forma de ordenar usando markdown?
A principio apenas usei uma um ordenador de texto.

**Comment by Codfect** [comment]
#68

**Comment by OfficialMarinho** [comment]
Boa pergunta... a ordenação dos links tem causado uma dor de cabeça imensa na contribuição por parte da comunidade.

Acredito que a única forma de ordenar seria manualmente mesmo. 😞

**Comment by OfficialMarinho** [comment]
Como ninguém apareceu com uma solução para esta sugestão de organização, estarei fechando essa issue.
